trigger:
  branches:
    include:
      - master

pool:
  name: Default

variables:
  AWS_ACCESS_KEY_ID: $(Access_key)
  AWS_SECRET_ACCESS_KEY: $(Secret_key)
  AWS_DEFAULT_REGION: 'ap-south-1'

stages:
  - stage: InstallAndApplyTerraform
    jobs:
      # Job to Install Terraform
      - job: InstallTerraformJob
        steps:
          - script: |
              echo "Installing Terraform"
              wget -O - https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
              echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
              sudo apt update && sudo apt install terraform -y
              terraform -version  # Verify Terraform installation
            displayName: 'Install Terraform'

      # Job to Install AWS CLI v2
      - job: InstallAWSCLIJob
        dependsOn: InstallTerraformJob  # Make sure AWS CLI installs after Terraform
        steps:
          - script: |
              echo "Installing AWS CLI v2"
              # Update the package index
              sudo apt update

              # Install dependencies
              sudo apt install unzip -y

              # Download the AWS CLI version 2 installer
              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"

              # Unzip the installer
              unzip awscliv2.zip

              # Run the installer
              sudo ./aws/install

              # Verify AWS CLI installation
              aws --version
            displayName: 'Install AWS CLI v2'

      # Job to Configure AWS CLI
      - job: ConfigureAWSCLIJob
        dependsOn: InstallAWSCLIJob  # Ensure this job runs after AWS CLI is installed
        steps:
          - script: |
              echo "Configuring AWS CLI with provided credentials"
              export AWS_ACCESS_KEY_ID=$(AWS_ACCESS_KEY_ID)
              export AWS_SECRET_ACCESS_KEY=$(AWS_SECRET_ACCESS_KEY)
              export AWS_DEFAULT_REGION=$(AWS_DEFAULT_REGION)

              # Run aws configure to set up credentials (non-interactive)
              aws configure set aws_access_key_id $(AWS_ACCESS_KEY_ID)
              aws configure set aws_secret_access_key $(AWS_SECRET_ACCESS_KEY)
              aws configure set region $(AWS_DEFAULT_REGION)

              # Verify AWS CLI credentials
              aws sts get-caller-identity
            displayName: 'Configure AWS CLI'

      # Job to Initialize and Apply Terraform
      - job: TerraformApplyJob
        dependsOn: ConfigureAWSCLIJob
        steps:
          # Terraform Init
          - script: |
              terraform init
            displayName: 'Initialize Terraform'

          # Terraform Plan
          - script: |
              terraform plan -out=tfplan
            displayName: 'Terraform Plan'

          # Terraform Apply
          - script: |
              terraform apply -auto-approve tfplan
            displayName: 'Terraform Apply'
