trigger:
  branches:
    include:
      - master
pool:
  name: Default
variables:
  AWS_SERVICE_CONNECTION: 'AWS-SC'
  AWS_DEFAULT_REGION: 'ap-south-1'
stages:
  - stage: InstallTerraform
    jobs:
      - job: InstallTerraformJob
        steps:
          - script: |
              # Install Terraform
              wget -O - https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
              echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
              sudo apt update && sudo apt install terraform -y
              terraform -version  # Verify Terraform installation
            displayName: 'Install Terraform'
  
  - stage: TerraformApply
    dependsOn: InstallTerraform 
    jobs:
      - job: TerraformApplyJob
        steps:
          - script: |
              echo "Setting up AWS environment variables..."
              export AWS_ACCESS_KEY_ID=$(AWS_ACCESS_KEY_ID)
              export AWS_SECRET_ACCESS_KEY=$(AWS_SECRET_ACCESS_KEY)
              export AWS_DEFAULT_REGION='$(AWS_DEFAULT_REGION)'
              echo "AWS environment variables set."
              displayName: 'Set AWS Credentials' 

          # Terraform Init
          - script: |
              terraform init
            displayName: 'Initialize Terraform'

          # Terraform Plan
          - script: |
              terraform plan -out=tfplan
            displayName: 'Terraform Plan'

          # Terraform Apply
          - script: |
              terraform apply -auto-approve tfplan
            displayName: 'Terraform Apply'
