trigger:
  branches:
    include:
      - master  # The pipeline will trigger when changes are pushed to the 'master' branch

pool:
  vmImage: 'ubuntu-latest'  # Use the Ubuntu VM image to run the pipeline

steps:
  - task: UseTerraform@0
    inputs:
      version: '1.10.5'  # Specify the version of Terraform to use

  - script: |
      terraform init  # Initialize Terraform
      terraform plan  # Generate a Terraform execution plan
      terraform apply -auto-approve  # Apply the plan without confirmation
    displayName: 'Terraform Apply'
    workingDirectory: $(Build.SourcesDirectory)  # Specify the working directory for Terraform
